#属性名：后要空一格写属性值
app:
  name: "web_app"
  mode: "dev"
  port: 8081
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "go_mysql"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 100